### ISSUE TITLE
Add Sponsors Paragraph

### ISSUE THREAD

**Issue by anpolimus** [drupal-ukraine/dcamp-site#30]
- Create Sponsor Item paragraph (Logo + Link to the sponsors page).
- Create Sponsor Section paragraph (Title + Background color + unlimited Sponsor Item paragraphs)
- Create Sponsor paragraph (unlimited Sponsor Section paragraph)
- Style it according to design.

![image](https://user-images.githubusercontent.com/3023950/52404919-d1a10400-2ad2-11e9-822b-65b588aa4e8b.png)

https://app.zeplin.io/project/5c4cbebfc7769b408463817d/screen/5c4cc1ee3f49dc410a23f945

**Comment by andriyun** [comment]
Almost done with it.
Need to add styles
I've stuck a little bit with rendering media field inside.
But let's discuss it in PR when it will be ready

**Comment by anpolimus** [comment]
@andriyun if you need any guidance or help - I or @ivan-berezhnov could always help.

**Comment by andriyun** [comment]
Ready to review #68

**Comment by ivan-berezhnov** [comment]
Implemented in DCK-26
