### ISSUE TITLE
Add slider paragraph.

### ISSUE THREAD

**Issue by d3-anatoliy-polyakov** [drupal-ukraine/dcamp-site#43]
We need to implement paragraph with image slider based on unlimited slides data.

Paragraphs:
Slider Item:
- Image
- Title
- Description

Slider:
- Title
- Slides

Try to find as simple slide js lib as it possible

**Comment by andriyun** [comment]
@anpolimus What the purposes for this paragraph? 
What king of slides it will be?

**Comment by anpolimus** [comment]
We are moving content from old camps to new website.
We will have landing page for each previous camp.
We will user slider for posting of photos section from camp.
It should be multivalue paragraph that should be rendered as slider (slick or antoher.)

**Comment by d3-anatoliy-polyakov** [comment]
this is done
