### ISSUE TITLE
Issue with main menu

### ISSUE THREAD

**Issue by Olena-SheWolf** [drupal-ukraine/dcamp-site#47]
Please see the screencast for details: https://drive.google.com/file/d/16yZ-KtLbjHHk4MDAYryTJgdHzbUduoWF/view?usp=sharing

**Comment by ivan-berezhnov** [comment]
Fixed
Hi @Olena-SheWolf  and @anpolimus please check and if all ok close issue

**Comment by ivan-berezhnov** [comment]
Hi @Olena-SheWolf and @anpolimus 
I think it fixed
please check and if all ok close issue
