### ISSUE TITLE
Implement successful payment page.

### ISSUE THREAD

**Issue by anpolimus** [drupal-ukraine/dcamp-site#48]
**What we have now:**
![image](https://user-images.githubusercontent.com/3023950/53160032-bdc7c880-35cf-11e9-904a-f147e993d905.png)

**What is good solution here:**
![image](https://user-images.githubusercontent.com/3023950/53160300-53635800-35d0-11e9-9468-3efe3fa277f8.png)

1. Replace top image with our logo.
https://www.dropbox.com/s/tfd4hg5xgtptq62/DCKyi2019_background.png?dl=0
2. Text.
Great News!
You just payed for your DrupalCampKyiv ticket
Please, reserve 25-26 of May at your calendar. You will have a lot of Drupal in your life at that date.
If you want to be a speaker please, send us your presentation notes here: http://drupalcampkyiv/en/node/add/presentations.
Please, check yourself at our facebook event and you will not loose important news.

3. add fb widget code
```
<div id="fb-root"></div>
<script async defer src="https://connect.facebook.net/uk_UA/sdk.js#xfbml=1&version=v3.2&appId=2020216808272525&autoLogAppEvents=1"></script>
<div class="fb-page" data-href="https://www.facebook.com/drupalcampkyiv/" data-tabs="events" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/drupalcampkyiv/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/drupalcampkyiv/">DrupalCamp Kyiv</a></blockquote></div>
```

**Comment by anpolimus** [comment]
Successful checkout template:
/dcamp-site/docroot/modules/contrib/commerce/modules/checkout/templates/commerce-checkout-completion-message.html.twig

**Comment by ivan-berezhnov** [comment]
![screencapture-dckyiv-docksal-checkout-6-complete-2019-02-22-09_28_20](https://user-images.githubusercontent.com/10132087/53226590-3be5a700-3684-11e9-95bb-d96c32399e3c.png)
![Uploading screencapture-dckyiv-docksal-checkout-6-complete-2019-02-22-09_27_43.png…]()

**Comment by ivan-berezhnov** [comment]
@anpolimus Can we close the ticket ?
