### ISSUE TITLE
Implement QR code to the order

### ISSUE THREAD

**Issue by d3-anatoliy-polyakov** [drupal-ukraine/dcamp-site#51]
- [ ] Investigate google chart service or library: https://github.com/pH-7/QRCode-Generator-PHP-Class
- [ ] Create Attendee paragraph type with fields:
   - Entity reference to User 
   - fallback First Name
   - fallback Last Name
   - fallback E-mail.
Attach reference to paragraph to the order item entity.
- [ ] Implement /user/{user}/my-tickets page
  Get all orders with = completed status
  Paragraph item based on count of order item value
  Add extra field to the paragraph item and render QR code at that field based on temporary data (for now, lets render md5());
- [ ] Generate QR code at order page based on order item data (many entrance tickets could be packed to one order)
text that should be packed to the QR code: order_id:order_item_delta

**Comment by anpolimus** [comment]
1. Add reference to attendee paragraph.
2. Add my tickets user page.
My tickets - display list of completed orders.
Show orders items and generated QR code for each order item.

**Comment by d3-anatoliy-polyakov** [comment]
this is done
