### ISSUE TITLE
My cart management improvements.

### ISSUE THREAD

**Issue by anpolimus** [drupal-ukraine/dcamp-site#60]
We have now basic cart functionality which is not comfortable for user.
We need to do next:
- [ ] Add ability to delete row in a cart.
- [ ] Add ability to change t-shirt size from the cart page.
![image](https://user-images.githubusercontent.com/3023950/53591569-fd2c8100-3b9c-11e9-9289-d370be4d3368.png)

**Comment by ivan-berezhnov** [comment]
Implemented by @andriyun
