### ISSUE TITLE
Add Timetable paragraph item.

### ISSUE THREAD

**Issue by d3-anatoliy-polyakov** [drupal-ukraine/dcamp-site#83]
1. Add **Timetable** paragraph.
 - Title
 - Timetable slot reference (unlimited).
2. Add **Timetable Slot** paragraph item.
 - Timeslot - text field
 - Description - formatted text
 - Background color - color field with predefined colors (#cc5447, #cca81a, #65a3bd, #a365bd, #ebebeb, #65bd6a, #c7b299)
 - Reference to Timetable presentation paragraph item
3. Add **Timetable Presentation** paragraph item
 

![image](https://user-images.githubusercontent.com/3023950/54915521-fd9c0b80-4eff-11e9-93c5-c70421087e6d.png)

Zepplin: https://app.zeplin.io/project/5c4cbebfc7769b408463817d/screen/5c4cc48018fc287b29151325

**Comment by ivan-berezhnov** [comment]
Implemented
